http:
  routers:
    # Router for mediasoup (for voice chat)
    mediasoup-router:
      # Change to a different subdomain and remove path later
      rule: "Host(`voice.executeit.ml`)"
      service: mediasoup
      middlewares:
        - mediasoup-auth

  services:
    # Service for mediasoup (for voice chat)
    mediasoup:
      loadBalancer:
        servers:
          # 172.17.0.1 is IP of the host
          - url: ${HOST_IP}

  middlewares:
    # Middlewares for mediasoup (for voice chat)
    mediasoup-auth:
      forwardAuth:
        address: https://api.executeit.ml/auth
        trustForwardHeader: true
